# Generated by Django 4.0.1 on 2022-01-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_active_listing_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, to='auctions.Listing'),
        ),
    ]
