# Generated by Django 4.0.1 on 2022-01-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_user_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
