# Generated by Django 4.0.1 on 2022-01-31 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_bid_time_created_alter_comment_time_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='img_url',
            field=models.URLField(blank=True, default='https://kaverisias.com/wp-content/uploads/2018/01/catalog-default-img.gif'),
        ),
    ]
