# Generated by Django 4.0.1 on 2022-02-25 23:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_remove_like_author_remove_like_posts_user_follow_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='follow',
        ),
        migrations.AddField(
            model_name='user',
            name='follow',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
