# Generated by Django 4.0.1 on 2022-01-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
