# Generated by Django 4.0.1 on 2022-01-20 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0018_profile_fb_url_profile_header_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='header_image',
            new_name='profile_pic',
        ),
    ]
